# Generated by Django 5.2.5 on 2025-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='@', max_length=100)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
